env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - airbnb-typescript
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  project: ./tsconfig.json
plugins:
  - react
  - '@typescript-eslint'
ignorePatterns:
    - vite.config.ts
settings:
  import/resolver:
    typescript: []
rules:
  react/react-in-jsx-scope: off
  semi:
    - error
    - never
  import/prefer-default-export: off
  import/no-default-export: error